# sample_data.py
# Realistic B2B SaaS warm lead records.
# Source types mirror where real buying-intent signals appear:
# G2 Review, Reddit r/SaaS, LinkedIn Post, ProductHunt Comment, Twitter/X Thread.
# Pain signals are verbatim-style quotes so outreach feels researched, not generic.

SAMPLE_LEADS = [
    {
        "name": "Marcus Holt",
        "company": "Funnelwise",
        "role": "Founder & CEO",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "Publicly posted on LinkedIn: 'Spending 4 hours a day manually qualifying inbound — there has to be a better way.'",
        "source_type": "LinkedIn Post",
        "pain_keywords": ["lead generation", "qualification", "inbound", "pipeline", "manual"],
        "seniority_weight": 10,
    },
    {
        "name": "Priya Nair",
        "company": "Dashmetrics",
        "role": "Head of Growth",
        "niche": "B2B SaaS",
        "customer_type": "growth teams",
        "pain_signal": "Left a G2 review of a competitor tool: 'We churn because we can never figure out which leads are actually ready to buy.'",
        "source_type": "G2 Review",
        "pain_keywords": ["churn", "lead scoring", "buying intent", "ready to buy", "conversion"],
        "seniority_weight": 8,
    },
    {
        "name": "Jordan Ellis",
        "company": "Stackly",
        "role": "Co-Founder",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "Posted in r/SaaS: 'Our onboarding drop-off is brutal. We get signups but nobody activates. Any tools actually solving this?'",
        "source_type": "Reddit r/SaaS",
        "pain_keywords": ["onboarding", "activation", "drop-off", "signups", "convert"],
        "seniority_weight": 10,
    },
    {
        "name": "Sofia Brennan",
        "company": "Recurrify",
        "role": "CEO",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "ProductHunt comment on a competitor: 'Would love this but we need it to actually detect intent before the lead goes cold.'",
        "source_type": "ProductHunt Comment",
        "pain_keywords": ["intent", "lead cold", "detection", "pipeline", "outbound"],
        "seniority_weight": 10,
    },
    {
        "name": "Tariq Osei",
        "company": "CloseLoop CRM",
        "role": "VP of Sales",
        "niche": "B2B SaaS",
        "customer_type": "sales teams",
        "pain_signal": "Twitter/X thread: 'Hot take: most B2B sales teams are calling leads who will never buy while ignoring the ones who are ready. We had this exact problem.'",
        "source_type": "Twitter/X Thread",
        "pain_keywords": ["sales", "lead quality", "cold outreach", "buying signal", "pipeline"],
        "seniority_weight": 8,
    },
    {
        "name": "Anika Petrov",
        "company": "Growthpad",
        "role": "Founder",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "Posted on LinkedIn: 'Tried Apollo, tried Clay. Still spending $3k/mo on outbound with a 0.8% reply rate. Something is broken.'",
        "source_type": "LinkedIn Post",
        "pain_keywords": ["outbound", "cold email", "reply rate", "lead generation", "apollo", "clay"],
        "seniority_weight": 10,
    },
    {
        "name": "Leon Marchetti",
        "company": "Pipeforge",
        "role": "Head of Revenue",
        "niche": "B2B SaaS",
        "customer_type": "revenue teams",
        "pain_signal": "G2 review of a sequencing tool: 'Zero visibility into which accounts are actually showing intent. We're flying blind on outbound.'",
        "source_type": "G2 Review",
        "pain_keywords": ["intent", "outbound", "pipeline", "visibility", "account", "lead scoring"],
        "seniority_weight": 8,
    },
    {
        "name": "Claire Dumont",
        "company": "Segmentix",
        "role": "Co-Founder & CTO",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "Reddit r/startups: 'We have 400 trial users. I have no idea which 20 are likely to pay. Our scoring model is basically a coin flip.'",
        "source_type": "Reddit r/startups",
        "pain_keywords": ["trial", "conversion", "lead scoring", "churn", "activation", "onboarding"],
        "seniority_weight": 9,
    },
    {
        "name": "Daniel Kwon",
        "company": "RevStream AI",
        "role": "Founder",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "ProductHunt comment: 'We need warm leads not cold lists. Everyone is selling data — nobody is selling intent.'",
        "source_type": "ProductHunt Comment",
        "pain_keywords": ["warm leads", "cold outreach", "intent", "lead generation", "data"],
        "seniority_weight": 10,
    },
    {
        "name": "Isabel Torres",
        "company": "Scalepath",
        "role": "Director of Marketing",
        "niche": "B2B SaaS",
        "customer_type": "marketing teams",
        "pain_signal": "LinkedIn Post: 'MQL to SQL conversion just hit 6%. Either our ICP is wrong or we're nurturing the wrong people. Probably both.'",
        "source_type": "LinkedIn Post",
        "pain_keywords": ["MQL", "SQL", "conversion", "ICP", "nurturing", "lead quality"],
        "seniority_weight": 7,
    },
    {
        "name": "Finn O'Brien",
        "company": "Launchmetric SaaS",
        "role": "CEO",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "Twitter/X: 'Founder-led sales is exhausting when you don't know who to call first. Wish there was a signal layer on top of our CRM.'",
        "source_type": "Twitter/X Thread",
        "pain_keywords": ["founder-led sales", "CRM", "signal", "outbound", "pipeline", "lead generation"],
        "seniority_weight": 10,
    },
    {
        "name": "Natasha Romero",
        "company": "Clientbase Pro",
        "role": "Growth Lead",
        "niche": "B2B SaaS",
        "customer_type": "growth teams",
        "pain_signal": "G2 review: 'Great tool but we still have no idea which leads are in-market. The intent data is stale by the time it reaches us.'",
        "source_type": "G2 Review",
        "pain_keywords": ["intent data", "in-market", "lead scoring", "pipeline", "outbound"],
        "seniority_weight": 7,
    },
    {
        "name": "Ethan Park",
        "company": "Onboardly",
        "role": "Founder & CEO",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "Reddit r/SaaS: 'Onboarding is our biggest bottleneck. 70% of trials never see the core feature. We need to figure out who to rescue manually.'",
        "source_type": "Reddit r/SaaS",
        "pain_keywords": ["onboarding", "trial", "activation", "churn", "drop-off", "conversion"],
        "seniority_weight": 10,
    },
    {
        "name": "Camille Voss",
        "company": "Churnbuster Labs",
        "role": "Head of Customer Success",
        "niche": "B2B SaaS",
        "customer_type": "CS teams",
        "pain_signal": "LinkedIn post: 'Churn prediction models are great but they tell you after the customer has already decided to leave. Need earlier signals.'",
        "source_type": "LinkedIn Post",
        "pain_keywords": ["churn", "retention", "prediction", "early signal", "customer success"],
        "seniority_weight": 7,
    },
    {
        "name": "Ravi Sharma",
        "company": "Leadspark B2B",
        "role": "Co-Founder",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "ProductHunt: 'Upvoted. We're burning 20 hours a week on outbound research. If this actually finds warm leads it would pay for itself in one deal.'",
        "source_type": "ProductHunt Comment",
        "pain_keywords": ["outbound", "research", "warm leads", "lead generation", "time saving"],
        "seniority_weight": 10,
    },
    {
        "name": "Mia Chen",
        "company": "Converta SaaS",
        "role": "CEO",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "Twitter/X thread reply: 'Our biggest problem is not leads — it's that we can't tell which ones are serious buyers vs tire-kickers until 3 calls in.'",
        "source_type": "Twitter/X Thread",
        "pain_keywords": ["lead quality", "qualification", "conversion", "buyer intent", "pipeline"],
        "seniority_weight": 10,
    },
    {
        "name": "Tobias Kramer",
        "company": "SaaSGrid Analytics",
        "role": "VP Product",
        "niche": "B2B SaaS",
        "customer_type": "product teams",
        "pain_signal": "Reddit r/ProductManagement: 'We have usage data but no way to connect it to purchase intent. Feature usage ≠ buying intent and we keep confusing the two.'",
        "source_type": "Reddit r/ProductManagement",
        "pain_keywords": ["product analytics", "intent", "usage data", "conversion", "activation"],
        "seniority_weight": 7,
    },
    {
        "name": "Lena Haugen",
        "company": "NorthStar GTM",
        "role": "Founder",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "LinkedIn: 'Just fired our SDR team and going back to founder-led sales. The problem is I need better signal on who to target or it's the same mistake.'",
        "source_type": "LinkedIn Post",
        "pain_keywords": ["SDR", "founder-led sales", "signal", "outbound", "lead generation", "pipeline"],
        "seniority_weight": 10,
    },
    {
        "name": "Carlos Vega",
        "company": "Prospectly",
        "role": "Head of Sales",
        "niche": "B2B SaaS",
        "customer_type": "sales teams",
        "pain_signal": "G2 review: 'We're sending 500 cold emails a day with a 0.4% reply rate. We don't need more volume. We need better targeting.'",
        "source_type": "G2 Review",
        "pain_keywords": ["cold email", "reply rate", "targeting", "outbound", "lead quality"],
        "seniority_weight": 7,
    },
    {
        "name": "Yuki Tanaka",
        "company": "Loopflow",
        "role": "Co-Founder",
        "niche": "B2B SaaS",
        "customer_type": "founders",
        "pain_signal": "ProductHunt comment: 'This is exactly what we need. We just hired a VA to manually find leads but it takes 3 weeks to see results. Very open to automation here.'",
        "source_type": "ProductHunt Comment",
        "pain_keywords": ["automation", "lead generation", "manual research", "outbound", "warm leads"],
        "seniority_weight": 10,
    },
]
